// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// Simulation_Get_cpp
Rcpp::List Simulation_Get_cpp(Rcpp::List paramList);
RcppExport SEXP MAGENTA_Simulation_Get_cpp(SEXP paramListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type paramList(paramListSEXP);
    rcpp_result_gen = Rcpp::wrap(Simulation_Get_cpp(paramList));
    return rcpp_result_gen;
END_RCPP
}
// Simulation_Init_cpp
Rcpp::List Simulation_Init_cpp(Rcpp::List paramList);
RcppExport SEXP MAGENTA_Simulation_Init_cpp(SEXP paramListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type paramList(paramListSEXP);
    rcpp_result_gen = Rcpp::wrap(Simulation_Init_cpp(paramList));
    return rcpp_result_gen;
END_RCPP
}
// Simulation_Saved_Init_cpp
Rcpp::List Simulation_Saved_Init_cpp(Rcpp::List paramList);
RcppExport SEXP MAGENTA_Simulation_Saved_Init_cpp(SEXP paramListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type paramList(paramListSEXP);
    rcpp_result_gen = Rcpp::wrap(Simulation_Saved_Init_cpp(paramList));
    return rcpp_result_gen;
END_RCPP
}
// Simulation_Update_cpp
Rcpp::List Simulation_Update_cpp(Rcpp::List paramList);
RcppExport SEXP MAGENTA_Simulation_Update_cpp(SEXP paramListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type paramList(paramListSEXP);
    rcpp_result_gen = Rcpp::wrap(Simulation_Update_cpp(paramList));
    return rcpp_result_gen;
END_RCPP
}
