// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Simulation_Finalizer_cpp
Rcpp::List Simulation_Finalizer_cpp(Rcpp::List param_list);
RcppExport SEXP _magenta_Simulation_Finalizer_cpp(SEXP param_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type param_list(param_listSEXP);
    rcpp_result_gen = Rcpp::wrap(Simulation_Finalizer_cpp(param_list));
    return rcpp_result_gen;
END_RCPP
}
// Simulation_Get_cpp
Rcpp::List Simulation_Get_cpp(Rcpp::List param_list);
RcppExport SEXP _magenta_Simulation_Get_cpp(SEXP param_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type param_list(param_listSEXP);
    rcpp_result_gen = Rcpp::wrap(Simulation_Get_cpp(param_list));
    return rcpp_result_gen;
END_RCPP
}
// Simulation_Init_cpp
Rcpp::List Simulation_Init_cpp(Rcpp::List param_list);
RcppExport SEXP _magenta_Simulation_Init_cpp(SEXP param_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type param_list(param_listSEXP);
    rcpp_result_gen = Rcpp::wrap(Simulation_Init_cpp(param_list));
    return rcpp_result_gen;
END_RCPP
}
// Simulation_Saved_Init_cpp
Rcpp::List Simulation_Saved_Init_cpp(Rcpp::List param_list);
RcppExport SEXP _magenta_Simulation_Saved_Init_cpp(SEXP param_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type param_list(param_listSEXP);
    rcpp_result_gen = Rcpp::wrap(Simulation_Saved_Init_cpp(param_list));
    return rcpp_result_gen;
END_RCPP
}
// Simulation_Update_cpp
Rcpp::List Simulation_Update_cpp(Rcpp::List param_list);
RcppExport SEXP _magenta_Simulation_Update_cpp(SEXP param_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type param_list(param_listSEXP);
    rcpp_result_gen = Rcpp::wrap(Simulation_Update_cpp(param_list));
    return rcpp_result_gen;
END_RCPP
}
// test_barcode_from_PLAF
SEXP test_barcode_from_PLAF(Rcpp::NumericVector plaf, unsigned int n);
RcppExport SEXP _magenta_test_barcode_from_PLAF(SEXP plafSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type plaf(plafSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(test_barcode_from_PLAF(plaf, n));
    return rcpp_result_gen;
END_RCPP
}
// test_dependent_barcode_from_PLAF
SEXP test_dependent_barcode_from_PLAF(Rcpp::NumericVector plaf, unsigned int n);
RcppExport SEXP _magenta_test_dependent_barcode_from_PLAF(SEXP plafSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type plaf(plafSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(test_dependent_barcode_from_PLAF(plaf, n));
    return rcpp_result_gen;
END_RCPP
}
// test_recombinant_with_ibd
SEXP test_recombinant_with_ibd(SEXP barcode_1, SEXP barcode_2, unsigned int bl, unsigned int nl, unsigned int ib, Rcpp::NumericVector pc);
RcppExport SEXP _magenta_test_recombinant_with_ibd(SEXP barcode_1SEXP, SEXP barcode_2SEXP, SEXP blSEXP, SEXP nlSEXP, SEXP ibSEXP, SEXP pcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type barcode_1(barcode_1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type barcode_2(barcode_2SEXP);
    Rcpp::traits::input_parameter< unsigned int >::type bl(blSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nl(nlSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type ib(ibSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pc(pcSEXP);
    rcpp_result_gen = Rcpp::wrap(test_recombinant_with_ibd(barcode_1, barcode_2, bl, nl, ib, pc));
    return rcpp_result_gen;
END_RCPP
}
// test_generate_next_ibd
SEXP test_generate_next_ibd(unsigned int bl, unsigned int nl, unsigned int ib, Rcpp::NumericVector pc, unsigned int id);
RcppExport SEXP _magenta_test_generate_next_ibd(SEXP blSEXP, SEXP nlSEXP, SEXP ibSEXP, SEXP pcSEXP, SEXP idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type bl(blSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nl(nlSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type ib(ibSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pc(pcSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type id(idSEXP);
    rcpp_result_gen = Rcpp::wrap(test_generate_next_ibd(bl, nl, ib, pc, id));
    return rcpp_result_gen;
END_RCPP
}
// test_ibd_conversion
Rcpp::List test_ibd_conversion(SEXP barcode, unsigned int bl, unsigned int nl, unsigned int ib);
RcppExport SEXP _magenta_test_ibd_conversion(SEXP barcodeSEXP, SEXP blSEXP, SEXP nlSEXP, SEXP ibSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type barcode(barcodeSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type bl(blSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nl(nlSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type ib(ibSEXP);
    rcpp_result_gen = Rcpp::wrap(test_ibd_conversion(barcode, bl, nl, ib));
    return rcpp_result_gen;
END_RCPP
}
// population_get_genetics_ibd_df_n
Rcpp::List population_get_genetics_ibd_df_n(Rcpp::List param_list);
RcppExport SEXP _magenta_population_get_genetics_ibd_df_n(SEXP param_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type param_list(param_listSEXP);
    rcpp_result_gen = Rcpp::wrap(population_get_genetics_ibd_df_n(param_list));
    return rcpp_result_gen;
END_RCPP
}
// population_get_genetics_df_n
Rcpp::List population_get_genetics_df_n(Rcpp::List param_list);
RcppExport SEXP _magenta_population_get_genetics_df_n(SEXP param_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type param_list(param_listSEXP);
    rcpp_result_gen = Rcpp::wrap(population_get_genetics_df_n(param_list));
    return rcpp_result_gen;
END_RCPP
}
// test_bitset_serialisation
SEXP test_bitset_serialisation(SEXP x, unsigned int n);
RcppExport SEXP _magenta_test_bitset_serialisation(SEXP xSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(test_bitset_serialisation(x, n));
    return rcpp_result_gen;
END_RCPP
}
