#------------------------------------------------
#' Parameter List creation for MAGENTA simulation initialisation
#'
#' \code{Param_List_Simulation_Init_Create} creates suitable parameter list for
#' \code{Simulation_R} for the beginning of a simulation
#'
#' @param N Population size. Default = 1e4
#' @param years Length of simulation. Default = 1
#' @param eqSS Output of \code{Equilibrium_Steady_State_Create}
#' 
#' @export

Param_List_Simulation_Init_Create <- function(N = 1e+04, years = 1, ft = 0.4, eqSS)
{
  
  ## CHECKS ##
  ##---------------------------------------------
  if(class(eqSS)!="list") stop("eqSS is not of class list")
  if(!identical(names(eqSS),
                c("age_brackets","het_brackets","Smat",
                  "Dmat","Amat","Umat","Tmat","Pmat",
                  "IBmat","ICAmat","ICMmat","IDmat",
                  "Sv","Ev","Iv","MaternalImmunity"))) stop("Incorrect variable names within equilibrium.steady.state")
  dims.1 <- lapply(eqSS,function(x){return(dim(x)[1])})
  dims.2 <- lapply(eqSS,function(x){return(dim(x)[2])})
  if(unique(unlist(dims.1[grep("mat",names(eqSS))]))!=length(eqSS$age_brackets)) stop("Dimensions 1 error in equilibrium.stead.state matrices")
  if(unique(unlist(dims.2[grep("mat",names(eqSS))]))!=length(eqSS$het_brackets)) stop("Dimensions 2 error in equilibrium.stead.state matrices")
  
  numerics <- which(!unlist(lapply(eqSS,is.numeric)))
  if (length(numerics)!=0) stop(paste(names(numerics),"provided not numeric"))
  
  ##---------------------------------------------
  
  # Create paramlist
  paramList <- list(N = N, years = years, ft = ft, eqSS = eqSS)
  
  return(paramList)
  
}

#------------------------------------------------
#' Parameter List creation for MAGENTA simulation updating
#'
#' \code{Param_List_Simulation_Update_Create} creates suitable parameter list for
#' \code{Simulation_R} for continuing a simulation from memory within the active
#' session.
#'
#' @param years Length of simulation. Default = 1
#' @param statePtr Pointer for current model state as return by \code{Simulation_R}$Ptr
#' 
#' @export

Param_List_Simulation_Update_Create <- function(years = 1, ft = 0.4, statePtr)
{
  
  ## CHECKS ##
  ##---------------------------------------------
  if(class(statePtr)!="externalptr") stop("state.ptr is not of class externalptr")
  if(!is.numeric(years)) stop("years provided is not numeric")
  
  ##---------------------------------------------
  
  # Create paramlist
  paramList <- list(years = years, ft = ft, statePtr = statePtr)
  
  return(paramList)
  
}

#------------------------------------------------
#' Parameter List creation for MAGENTA simulation getting (saving to disk)
#'
#' \code{Param_List_Simulation_Get_Create} creates suitable parameter list for
#' \code{Simulation_R} for continuing a simulation from memory within the active
#' session.
#'
#' @param statePtr Pointer for current model state as return by \code{Simulation_R}$Ptr
#' 
#' @export

Param_List_Simulation_Get_Create <- function(statePtr)
{
  
  ## CHECKS ##
  ##---------------------------------------------
  if(class(statePtr)!="externalptr") stop("state.ptr is not of class externalptr")
  
  ##---------------------------------------------
  
  # Create paramlist
  paramList <- list(statePtr = statePtr)
  
  return(paramList)
  
}

#------------------------------------------------
#' Parameter List creation for loading saved MAGENTA simulation
#'
#' \code{Param_List_Simulation_Saved_Init_Create} creates suitable parameter list for
#' \code{Simulation_R} for continuing a simulation from memory within the active
#' session.
#'
#' @param years Length of simulation. Default = 1
#' @param savedState Saved state generated by \code{Simulation_R} when provided with 
#' a \code{Param_List_Simulation_Get_Create} parameter list
#' 
#' @export

Param_List_Simulation_Saved_Init_Create <- function(years = 1, ft = 0.4, savedState)
{
  
  ## CHECKS ##
  ##---------------------------------------------
  if(class(savedState)!="list") stop("savedState is not of class list")
  if(!is.numeric(years)) stop("years provided is not numeric")
  if(!identical(names(savedState),c("population_List","populations_event_and_strains_List","scourge_List","parameters_List"))) stop("Incorrect variable names within savedState")
 
  ## TODO: More checks here
  ##---------------------------------------------
  
  # Create paramlist
  paramList <- list(savedState = savedState,years = years, ft = ft )
  
  return(paramList)
  
}


#------------------------------------------------
#' Simulation_R function
#'
#' This function triggers the main MAGENTA simulation from the R side
#'
#' @param paramList Paramlist passed from \code{Param_List_Simulation_Init_Create}
#' or from \code{Param_List_Simulation_Update_Create}
#' @export

# The following commands are needed to ensure that the roxygen2
# package, which deals with documenting the package, does not conflict
# with the Rcpp package. Do not alter!
#' @useDynLib MAGENTA
#' @importFrom Rcpp evalCpp
#' @exportPattern '^[[:alpha:]]+'

Simulation_R <- function(paramList)
{
  
  # check that this function is working
  print("R function is working!")
  stopifnot(is.list(paramList))
  
  ## Decide whether the paramList is from initialisation, memory-continutation or continuation
  
  ## -----------------------------------
  ## 1. From initialisation
  ## -----------------------------------
  if(!is.null(paramList$eqSS)){
    
    ## Check if paramlist is correct length and has right variable names
    stopifnot(is.list(paramList))
    if(length(paramList)==4)
    {
      stopifnot(identical(names(paramList), c("N", "years", "ft", "eqSS")))  
    }
    # if it is length one it may be an unpacked list in which case unpack and check
    # this might happen in the future when a list of paramLists is fed directly to this
    # fucntion in a cluster way
    else if(length(paramList)==1)
    {
      paramList <- paramList[[1]]
      stopifnot(identical(names(paramList), c("N", "years","ft", "eqSS")))  
    } 
    else 
    {
      stop("paramList not correct length")
    }
    
    # ---------------------- RUN C CODE ------------------------------------- #
    
    # call Rcpp command with input list
    rawOutput <- Simulation_Init_cpp(paramList)
    
    # ----------------------------------------------------------------------- #
    
    
  }
  
  ## -----------------------------------
  ## 2. From memory-continutation
  ## -----------------------------------
  if(!is.null(paramList$years) & !is.null(paramList$statePtr)){
    
    ## Check if paramlist is correct length and has right variable names
    stopifnot(is.list(paramList))
    if(length(paramList)==3)
    {
      stopifnot(identical(names(paramList), c("years","ft", "statePtr")))  
    }
    else 
    {
      stop("paramList not correct length")
    }
    
    # ---------------------- RUN C CODE ------------------------------------- #
    
    # call Rcpp command with input list
    rawOutput <- Simulation_Update_cpp(paramList)
    
    # ----------------------------------------------------------------------- #
    
  }
  
  ## -----------------------------------
  ## 3. From memory-continutation to saving
  ## -----------------------------------
  if(is.null(paramList$years) & !is.null(paramList$statePtr)){
    
    ## Check if paramlist is correct length and has right variable names
    stopifnot(is.list(paramList))
    if(length(paramList)==1)
    {
      stopifnot(identical(names(paramList), c("statePtr")))  
    }
    else 
    {
      stop("paramList not correct length")
    } 
    
    # ---------------------- RUN C CODE ------------------------------------- #
    
    # call Rcpp command with input list
    rawOutput <- Simulation_Get_cpp(paramList)
    
    # ----------------------------------------------------------------------- #
    
  }
  
  ## -----------------------------------
  ## 4. From saved state
  ## -----------------------------------
  if(!is.null(paramList$savedState)){
    
    ## Check if paramlist is correct length and has right variable names
    stopifnot(is.list(paramList))
    if(length(paramList)==3)
    {
      stopifnot(identical(names(paramList), c("savedState","years", "ft")))  
    }
    else 
    {
      stop("paramList not correct length")
    } 
    
    # ---------------------- RUN C CODE ------------------------------------- #
    
    # call Rcpp command with input list
    rawOutput <- Simulation_Saved_Init_cpp(paramList)
    
    # ----------------------------------------------------------------------- #
    
  }
  
  ## Catch if parameter list not matched well
  if(is.null(rawOutput)) stop("No matching parameter list handler found within Simulation_R")
  
  # return rawOutput
  return(rawOutput)
}