# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Returns whole model to R in series of nested lists
#'
#' @param paramList parameter list generated with \code{Param_List_Simulation_Get_Create}
#' @return list of 4 lists with the entire model state
#' @export
Simulation_Get_cpp <- function(paramList) {
    .Call('_MAGENTA_Simulation_Get_cpp', PACKAGE = 'MAGENTA', paramList)
}

#' Creates initial model simulation using paramter list provided
#'
#' @param paramList parameter list generated with \code{Param_List_Simulation_Init_Create}
#' @return list with ptr to model state and loggers describing the current model state
#' @export
Simulation_Init_cpp <- function(paramList) {
    .Call('_MAGENTA_Simulation_Init_cpp', PACKAGE = 'MAGENTA', paramList)
}

Simulation_Saved_Init_cpp <- function(paramList) {
    .Call('_MAGENTA_Simulation_Saved_Init_cpp', PACKAGE = 'MAGENTA', paramList)
}

#' Continues simulation forward for as long as specified in paramList
#'
#' @param paramList parameter list generated with \code{Param_List_Simulation_Update_Create}
#' @return list with ptr to model state and loggers describing the current model state
#' @export
Simulation_Update_cpp <- function(paramList) {
    .Call('_MAGENTA_Simulation_Update_cpp', PACKAGE = 'MAGENTA', paramList)
}

test_barcode_from_PLAF <- function(plaf, n) {
    .Call('_MAGENTA_test_barcode_from_PLAF', PACKAGE = 'MAGENTA', plaf, n)
}

test_bitset_serialisation <- function(x, n) {
    .Call('_MAGENTA_test_bitset_serialisation', PACKAGE = 'MAGENTA', x, n)
}

