# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Returns whole model to R in series of nested lists
#'
#' @param param_list parameter list generated with \code{param_list_simulation_finalizer_create}
#' @return list of 1 confirming finalizer has finished
#' @export
Simulation_Finalizer_cpp <- function(param_list) {
    .Call('_magenta_Simulation_Finalizer_cpp', PACKAGE = 'magenta', param_list)
}

#' Returns whole model to R in series of nested lists
#'
#' @param param_list parameter list generated with \code{Param_List_Simulation_Get_Create}
#' @return list of 4 lists with the entire model state
#' @export
Simulation_Get_cpp <- function(param_list) {
    .Call('_magenta_Simulation_Get_cpp', PACKAGE = 'magenta', param_list)
}

#' Creates initial model simulation using paramter list provided
#'
#' @param param_list parameter list generated with \code{Param_List_Simulation_Init_Create}
#' @return list with ptr to model state and loggers describing the current model state
#' @export
Simulation_Init_cpp <- function(param_list) {
    .Call('_magenta_Simulation_Init_cpp', PACKAGE = 'magenta', param_list)
}

Simulation_Saved_Init_cpp <- function(param_list) {
    .Call('_magenta_Simulation_Saved_Init_cpp', PACKAGE = 'magenta', param_list)
}

#' Continues simulation forward for as long as specified in param_list
#'
#' @param param_list parameter list generated with \code{Param_List_Simulation_Update_Create}
#' @return list with ptr to model state and loggers describing the current model state
#' @export
Simulation_Update_cpp <- function(param_list) {
    .Call('_magenta_Simulation_Update_cpp', PACKAGE = 'magenta', param_list)
}

test_barcode_from_PLAF <- function(plaf, n) {
    .Call('_magenta_test_barcode_from_PLAF', PACKAGE = 'magenta', plaf, n)
}

test_recombinant_with_ibd <- function(barcode_1, barcode_2, bl, nl, ib, pc) {
    .Call('_magenta_test_recombinant_with_ibd', PACKAGE = 'magenta', barcode_1, barcode_2, bl, nl, ib, pc)
}

test_generate_next_ibd <- function(bl, nl, ib, pc, id) {
    .Call('_magenta_test_generate_next_ibd', PACKAGE = 'magenta', bl, nl, ib, pc, id)
}

test_ibd_conversion <- function(barcode, bl, nl, ib) {
    .Call('_magenta_test_ibd_conversion', PACKAGE = 'magenta', barcode, bl, nl, ib)
}

#' Returns the population's parasite genetics for ibd style summarised by pibd for given sample size and state
#'
#' @param param_list param_list containing statePtr, sample_size, and sample_states
#' @return list of population information
#' @export
population_get_genetics_ibd_df_n <- function(param_list) {
    .Call('_magenta_population_get_genetics_ibd_df_n', PACKAGE = 'magenta', param_list)
}

#' Returns the population's parasite genetics summarised by coi for given sample size and state
#'
#' @param param_list param_list containing statePtr, sample_size, and sample_states
#' @return list of population information
#' @export
population_get_genetics_df_n <- function(param_list) {
    .Call('_magenta_population_get_genetics_df_n', PACKAGE = 'magenta', param_list)
}

test_bitset_serialisation <- function(x, n) {
    .Call('_magenta_test_bitset_serialisation', PACKAGE = 'magenta', x, n)
}

