# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Returns whole model to R in series of nested lists
#'
#' @param paramList parameter list generated with \code{Param_List_Simulation_Get_Create}
#' @return list of 4 lists with the entire model state
#' @export
Simulation_Get_cpp <- function(paramList) {
    .Call('_MAGENTA_Simulation_Get_cpp', PACKAGE = 'MAGENTA', paramList)
}

#' Creates initial model simulation using paramter list provided
#'
#' @param paramList parameter list generated with \code{Param_List_Simulation_Init_Create}
#' @return list with ptr to model state and loggers describing the current model state
#' @export
Simulation_Init_cpp <- function(paramList) {
    .Call('_MAGENTA_Simulation_Init_cpp', PACKAGE = 'MAGENTA', paramList)
}

Simulation_Saved_Init_cpp <- function(paramList) {
    .Call('_MAGENTA_Simulation_Saved_Init_cpp', PACKAGE = 'MAGENTA', paramList)
}

#' Continues simulation forward for as long as specified in paramList
#'
#' @param paramList parameter list generated with \code{Param_List_Simulation_Update_Create}
#' @return list with ptr to model state and loggers describing the current model state
#' @export
Simulation_Update_cpp <- function(paramList) {
    .Call('_MAGENTA_Simulation_Update_cpp', PACKAGE = 'MAGENTA', paramList)
}

test_barcode_from_PLAF <- function(plaf, n) {
    .Call('_MAGENTA_test_barcode_from_PLAF', PACKAGE = 'MAGENTA', plaf, n)
}

test_recombinant_with_ibd <- function(barcode_1, barcode_2, bl, nl, ib, pc) {
    .Call('_MAGENTA_test_recombinant_with_ibd', PACKAGE = 'MAGENTA', barcode_1, barcode_2, bl, nl, ib, pc)
}

test_generate_next_ibd <- function(bl, nl, ib, pc, id) {
    .Call('_MAGENTA_test_generate_next_ibd', PACKAGE = 'MAGENTA', bl, nl, ib, pc, id)
}

test_ibd_conversion <- function(barcode, bl, nl, ib) {
    .Call('_MAGENTA_test_ibd_conversion', PACKAGE = 'MAGENTA', barcode, bl, nl, ib)
}

#' Returns the population's parasite genetics for ibd style summarised by pibd for given sample size and state
#'
#' @param paramList paramList containing statePtr, sample_size, and sample_states
#' @return list of population information
#' @export
population_get_genetics_ibd_df_n <- function(paramList) {
    .Call('_MAGENTA_population_get_genetics_ibd_df_n', PACKAGE = 'MAGENTA', paramList)
}

#' Returns the population's parasite genetics summarised by coi for given sample size and state
#'
#' @param paramList paramList containing statePtr, sample_size, and sample_states
#' @return list of population information
#' @export
population_get_genetics_df_n <- function(paramList) {
    .Call('_MAGENTA_population_get_genetics_df_n', PACKAGE = 'MAGENTA', paramList)
}

test_bitset_serialisation <- function(x, n) {
    .Call('_MAGENTA_test_bitset_serialisation', PACKAGE = 'MAGENTA', x, n)
}

